name: C++ Build CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt update && sudo apt install libboost-all-dev nlohmann-json3-dev

      - name: Build with Make
        run: make all
